### ISSUE TITLE
CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead   from cryptography.utils import int_from_bytes

### ISSUE THREAD

**Issue by sirishageeth** [data-science-on-aws/data-science-on-aws#237]
When I run 01_setup_dependencies, I get the following error:

CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes 

error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-p556_z83/termcolor_6e020657f5c345abad744de44dec15b6/setup.py", line 53, in <module>
          'Topic :: Terminals'
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 466, in __init__
          for k, v in attrs.items()
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 885, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 884, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

Any pointers on how I can resolve this issue is greatly appreciated.

Thanks.

**Comment by cfregly** [comment]
interesting.  need to track this down.

@antje have you seen this before?

**Comment by cfregly** [comment]
@sirishageeth do you have a screenshot?  where are you running this?  

I'm trying to reproduce - and I see the warning, but i am able to proceed.

send some more data and we'll try to debug this.
