### ISSUE TITLE
06_prepare/02_Prepare_Dataset_BERT_Scikit_ScriptMode_FeatureStore.ipynb

### ISSUE THREAD

**Issue by victen18** [data-science-on-aws/data-science-on-aws#244]
The following error is inevitable after so many tries...tried to install numpy version 1.19.2, however error message is same. 

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/miniconda3/lib/python3.7/site-packages/numpy-1.19.2.dist-info/METADATA'
Traceback (most recent call last):
  File "/opt/ml/processing/input/code/preprocess-scikit-text-to-bert-feature-store.py", line 31, in <module>
    subprocess.check_call([sys.executable, "-m", "pip", "install", "transformers==3.5.1"])
  File "/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/miniconda3/bin/python3', '-m', 'pip', 'install', 'transformers==3.5.1']' returned non-zero exit status 1.

**Comment by victen18** [comment]
Issue was resolved with some changes in code at my end.
